package opc

// CONTENT_TYPE is a marker type used to namespace OPC content type constants.
type CONTENT_TYPE struct{}

// ContentType is the sole instance of CONTENT_TYPE, providing access to the
// content type constant namespace in Go notation (e.g. opc.ContentType.WML_DOCUMENT).
var ContentType CONTENT_TYPE

const (
	CT_BMP                          = "image/bmp"
	CT_DML_CHART                    = "application/vnd.openxmlformats-officedocument.drawingml.chart+xml"
	CT_DML_CHARTSHAPES              = "application/vnd.openxmlformats-officedocument.drawingml.chartshapes+xml"
	CT_DML_DIAGRAM_COLORS           = "application/vnd.openxmlformats-officedocument.drawingml.diagramColors+xml"
	CT_DML_DIAGRAM_DATA             = "application/vnd.openxmlformats-officedocument.drawingml.diagramData+xml"
	CT_DML_DIAGRAM_LAYOUT           = "application/vnd.openxmlformats-officedocument.drawingml.diagramLayout+xml"
	CT_DML_DIAGRAM_STYLE            = "application/vnd.openxmlformats-officedocument.drawingml.diagramStyle+xml"
	CT_GIF                          = "image/gif"
	CT_JPEG                         = "image/jpeg"
	CT_MS_PHOTO                     = "image/vnd.ms-photo"
	CT_OFC_CUSTOM_PROPERTIES        = "application/vnd.openxmlformats-officedocument.custom-properties+xml"
	CT_OFC_CUSTOM_XML_PROPERTIES    = "application/vnd.openxmlformats-officedocument.customXmlProperties+xml"
	CT_OFC_DRAWING                  = "application/vnd.openxmlformats-officedocument.drawing+xml"
	CT_OFC_EXTENDED_PROPERTIES      = "application/vnd.openxmlformats-officedocument.extended-properties+xml"
	CT_OFC_OLE_OBJECT               = "application/vnd.openxmlformats-officedocument.oleObject"
	CT_OFC_PACKAGE                  = "application/vnd.openxmlformats-officedocument.package"
	CT_OFC_THEME                    = "application/vnd.openxmlformats-officedocument.theme+xml"
	CT_OFC_THEME_OVERRIDE           = "application/vnd.openxmlformats-officedocument.themeOverride+xml"
	CT_OFC_VML_DRAWING              = "application/vnd.openxmlformats-officedocument.vmlDrawing"
	CT_OPC_CORE_PROPERTIES          = "application/vnd.openxmlformats-package.core-properties+xml"
	CT_OPC_DIGITAL_SIGNATURE_CERT   = "application/vnd.openxmlformats-package.digital-signature-certificate"
	CT_OPC_DIGITAL_SIGNATURE_ORIGIN = "application/vnd.openxmlformats-package.digital-signature-origin"
	CT_OPC_DIGITAL_SIGNATURE_XML    = "application/vnd.openxmlformats-package.digital-signature-xmlsignature+xml"
	CT_OPC_RELATIONSHIPS            = "application/vnd.openxmlformats-package.relationships+xml"
	CT_PML_COMMENTS                 = "application/vnd.openxmlformats-officedocument.presentationml.comments+xml"
	CT_PML_COMMENT_AUTHORS          = "application/vnd.openxmlformats-officedocument.presentationml.commentAuthors+xml"
	CT_PML_HANDOUT_MASTER           = "application/vnd.openxmlformats-officedocument.presentationml.handoutMaster+xml"
	CT_PML_NOTES_MASTER             = "application/vnd.openxmlformats-officedocument.presentationml.notesMaster+xml"
	CT_PML_NOTES_SLIDE              = "application/vnd.openxmlformats-officedocument.presentationml.notesSlide+xml"
	CT_PML_PRESENTATION_MAIN        = "application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"
	CT_PML_PRES_PROPS               = "application/vnd.openxmlformats-officedocument.presentationml.presProps+xml"
	CT_PML_PRINTER_SETTINGS         = "application/vnd.openxmlformats-officedocument.presentationml.printerSettings"
	CT_PML_SLIDE                    = "application/vnd.openxmlformats-officedocument.presentationml.slide+xml"
	CT_PML_SLIDESHOW_MAIN           = "application/vnd.openxmlformats-officedocument.presentationml.slideshow.main+xml"
	CT_PML_SLIDE_LAYOUT             = "application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"
	CT_PML_SLIDE_MASTER             = "application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"
	CT_PML_SLIDE_UPDATE_INFO        = "application/vnd.openxmlformats-officedocument.presentationml.slideUpdateInfo+xml"
	CT_PML_TABLE_STYLES             = "application/vnd.openxmlformats-officedocument.presentationml.tableStyles+xml"
	CT_PML_TAGS                     = "application/vnd.openxmlformats-officedocument.presentationml.tags+xml"
	CT_PML_TEMPLATE_MAIN            = "application/vnd.openxmlformats-officedocument.presentationml.template.main+xml"
	CT_PML_VIEW_PROPS               = "application/vnd.openxmlformats-officedocument.presentationml.viewProps+xml"
	CT_PNG                          = "image/png"
	CT_SML_CALC_CHAIN               = "application/vnd.openxmlformats-officedocument.spreadsheetml.calcChain+xml"
	CT_SML_CHARTSHEET               = "application/vnd.openxmlformats-officedocument.spreadsheetml.chartsheet+xml"
	CT_SML_COMMENTS                 = "application/vnd.openxmlformats-officedocument.spreadsheetml.comments+xml"
	CT_SML_CONNECTIONS              = "application/vnd.openxmlformats-officedocument.spreadsheetml.connections+xml"
	CT_SML_CUSTOM_PROPERTY          = "application/vnd.openxmlformats-officedocument.spreadsheetml.customProperty"
	CT_SML_DIALOGSHEET              = "application/vnd.openxmlformats-officedocument.spreadsheetml.dialogsheet+xml"
	CT_SML_EXTERNAL_LINK            = "application/vnd.openxmlformats-officedocument.spreadsheetml.externalLink+xml"
	CT_SML_PIVOT_CACHE_DEFINITION   = "application/vnd.openxmlformats-officedocument.spreadsheetml.pivotCacheDefinition+xml"
	CT_SML_PIVOT_CACHE_RECORDS      = "application/vnd.openxmlformats-officedocument.spreadsheetml.pivotCacheRecords+xml"
	CT_SML_PIVOT_TABLE              = "application/vnd.openxmlformats-officedocument.spreadsheetml.pivotTable+xml"
	CT_SML_PRINTER_SETTINGS         = "application/vnd.openxmlformats-officedocument.spreadsheetml.printerSettings"
	CT_SML_QUERY_TABLE              = "application/vnd.openxmlformats-officedocument.spreadsheetml.queryTable+xml"
	CT_SML_REVISION_HEADERS         = "application/vnd.openxmlformats-officedocument.spreadsheetml.revisionHeaders+xml"
	CT_SML_REVISION_LOG             = "application/vnd.openxmlformats-officedocument.spreadsheetml.revisionLog+xml"
	CT_SML_SHARED_STRINGS           = "application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"
	CT_SML_SHEET                    = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
	CT_SML_SHEET_MAIN               = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"
	CT_SML_SHEET_METADATA           = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheetMetadata+xml"
	CT_SML_STYLES                   = "application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"
	CT_SML_TABLE                    = "application/vnd.openxmlformats-officedocument.spreadsheetml.table+xml"
	CT_SML_TABLE_SINGLE_CELLS       = "application/vnd.openxmlformats-officedocument.spreadsheetml.tableSingleCells+xml"
	CT_SML_TEMPLATE_MAIN            = "application/vnd.openxmlformats-officedocument.spreadsheetml.template.main+xml"
	CT_SML_USER_NAMES               = "application/vnd.openxmlformats-officedocument.spreadsheetml.userNames+xml"
	CT_SML_VOLATILE_DEPENDENCIES    = "application/vnd.openxmlformats-officedocument.spreadsheetml.volatileDependencies+xml"
	CT_SML_WORKSHEET                = "application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"
	CT_TIFF                         = "image/tiff"
	CT_WML_COMMENTS                 = "application/vnd.openxmlformats-officedocument.wordprocessingml.comments+xml"
	CT_WML_DOCUMENT                 = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
	CT_WML_DOCUMENT_GLOSSARY        = "application/vnd.openxmlformats-officedocument.wordprocessingml.document.glossary+xml"
	CT_WML_DOCUMENT_MAIN            = "application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"
	CT_WML_ENDNOTES                 = "application/vnd.openxmlformats-officedocument.wordprocessingml.endnotes+xml"
	CT_WML_FONT_TABLE               = "application/vnd.openxmlformats-officedocument.wordprocessingml.fontTable+xml"
	CT_WML_FOOTER                   = "application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"
	CT_WML_FOOTNOTES                = "application/vnd.openxmlformats-officedocument.wordprocessingml.footnotes+xml"
	CT_WML_HEADER                   = "application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"
	CT_WML_NUMBERING                = "application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"
	CT_WML_PRINTER_SETTINGS         = "application/vnd.openxmlformats-officedocument.wordprocessingml.printerSettings"
	CT_WML_SETTINGS                 = "application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"
	CT_WML_STYLES                   = "application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"
	CT_WML_WEB_SETTINGS             = "application/vnd.openxmlformats-officedocument.wordprocessingml.webSettings+xml"
	CT_XML                          = "application/xml"
	CT_X_EMF                        = "image/x-emf"
	CT_X_FONTDATA                   = "application/x-fontdata"
	CT_X_FONT_TTF                   = "application/x-font-ttf"
	CT_X_WMF                        = "image/x-wmf"
)

// NAMESPACE is a marker type used to namespace XML namespace constants.
type NAMESPACE struct{}

// Namespace is the sole instance of NAMESPACE for accessing XML namespace URIs.
var Namespace NAMESPACE

const (
	NS_DML_WORD_PROCESSING_DRAWING = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"
	NS_OFC_RELATIONSHIPS           = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
	NS_OPC_RELATIONSHIPS           = "http://schemas.openxmlformats.org/package/2006/relationships"
	NS_OPC_CONTENT_TYPES           = "http://schemas.openxmlformats.org/package/2006/content-types"
	NS_WML_MAIN                    = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
)

// RELATIONSHIP_TARGET_MODE is a marker type for relationship target mode constants.
type RELATIONSHIP_TARGET_MODE struct{}

// RelationshipTargetMode provides access to relationship target mode constants.
var RelationshipTargetMode RELATIONSHIP_TARGET_MODE

const (
	// RTM_EXTERNAL indicates a relationship targets an external resource.
	RTM_EXTERNAL = "External"
	// RTM_INTERNAL indicates a relationship targets a part inside the package.
	RTM_INTERNAL = "Internal"
)

// RELATIONSHIP_TYPE is a marker type for relationship type URI constants.
type RELATIONSHIP_TYPE struct{}

// RelationshipType provides access to relationship type URI constants.
var RelationshipType RELATIONSHIP_TYPE

const (
	RT_AUDIO                  = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/audio"
	RT_A_F_CHUNK              = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/aFChunk"
	RT_CALC_CHAIN             = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/calcChain"
	RT_CERTIFICATE            = "http://schemas.openxmlformats.org/package/2006/relationships/digital-signature/certificate"
	RT_CHART                  = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/chart"
	RT_CHARTSHEET             = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/chartsheet"
	RT_CHART_USER_SHAPES      = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/chartUserShapes"
	RT_COMMENTS               = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments"
	RT_COMMENT_AUTHORS        = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/commentAuthors"
	RT_CONNECTIONS            = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/connections"
	RT_CONTROL                = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/control"
	RT_CORE_PROPERTIES        = "http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties"
	RT_CUSTOM_PROPERTIES      = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/custom-properties"
	RT_CUSTOM_PROPERTY        = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/customProperty"
	RT_CUSTOM_XML             = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/customXml"
	RT_CUSTOM_XML_PROPS       = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/customXmlProps"
	RT_DIAGRAM_COLORS         = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/diagramColors"
	RT_DIAGRAM_DATA           = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/diagramData"
	RT_DIAGRAM_LAYOUT         = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/diagramLayout"
	RT_DIAGRAM_QUICK_STYLE    = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/diagramQuickStyle"
	RT_DIALOGSHEET            = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/dialogsheet"
	RT_DRAWING                = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing"
	RT_ENDNOTES               = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/endnotes"
	RT_EXTENDED_PROPERTIES    = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties"
	RT_EXTERNAL_LINK          = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/externalLink"
	RT_FONT                   = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/font"
	RT_FONT_TABLE             = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable"
	RT_FOOTER                 = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer"
	RT_FOOTNOTES              = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/footnotes"
	RT_GLOSSARY_DOCUMENT      = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/glossaryDocument"
	RT_HANDOUT_MASTER         = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/handoutMaster"
	RT_HEADER                 = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/header"
	RT_HYPERLINK              = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink"
	RT_IMAGE                  = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/image"
	RT_NOTES_MASTER           = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesMaster"
	RT_NOTES_SLIDE            = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesSlide"
	RT_NUMBERING              = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering"
	RT_OFFICE_DOCUMENT        = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"
	RT_OLE_OBJECT             = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/oleObject"
	RT_ORIGIN                 = "http://schemas.openxmlformats.org/package/2006/relationships/digital-signature/origin"
	RT_PACKAGE                = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/package"
	RT_PIVOT_CACHE_DEFINITION = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/pivotCacheDefinition"
	RT_PIVOT_CACHE_RECORDS    = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/spreadsheetml/pivotCacheRecords"
	RT_PIVOT_TABLE            = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/pivotTable"
	RT_PRES_PROPS             = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/presProps"
	RT_PRINTER_SETTINGS       = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/printerSettings"
	RT_QUERY_TABLE            = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/queryTable"
	RT_REVISION_HEADERS       = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/revisionHeaders"
	RT_REVISION_LOG           = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/revisionLog"
	RT_SETTINGS               = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings"
	RT_SHARED_STRINGS         = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings"
	RT_SHEET_METADATA         = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/sheetMetadata"
	RT_SIGNATURE              = "http://schemas.openxmlformats.org/package/2006/relationships/digital-signature/signature"
	RT_SLIDE                  = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide"
	RT_SLIDE_LAYOUT           = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout"
	RT_SLIDE_MASTER           = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster"
	RT_SLIDE_UPDATE_INFO      = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideUpdateInfo"
	RT_STYLES                 = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles"
	RT_TABLE                  = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/table"
	RT_TABLE_SINGLE_CELLS     = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/tableSingleCells"
	RT_TABLE_STYLES           = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/tableStyles"
	RT_TAGS                   = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/tags"
	RT_THEME                  = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme"
	RT_THEME_OVERRIDE         = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/themeOverride"
	RT_THUMBNAIL              = "http://schemas.openxmlformats.org/package/2006/relationships/metadata/thumbnail"
	RT_USERNAMES              = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/usernames"
	RT_VIDEO                  = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/video"
	RT_VIEW_PROPS             = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/viewProps"
	RT_VML_DRAWING            = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/vmlDrawing"
	RT_VOLATILE_DEPENDENCIES  = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/volatileDependencies"
	RT_WEB_SETTINGS           = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/webSettings"
	RT_WORKSHEET_SOURCE       = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheetSource"
	RT_XML_MAPS               = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/xmlMaps"
)
